name: CI

on:
  push:
    branches:
      - main
      -- feature
      -- github-action
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo info
        run: |
          node -v || true
          npm -v || true
          ls -la
